/camera_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
    exposure_time: 3000
    gain: 8.0

/serial_driver:
  ros__parameters:
    timestamp_offset: 0.006
    device_name: /dev/ttyACM0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"

/armor_detector:
  ros__parameters:
    debug: false
    debug_image_fps: 30.0
    debug_publish_result_img: false
    debug_publish_binary_img: false
    debug_publish_number_img: false

    detect_color: 0
    binary_thres: 80

    light.min_ratio: 0.1
    armor.min_light_ratio: 0.8

    classifier_threshold: 0.8
    ignore_classes: ["negative"]

/armor_tracker:
  ros__parameters:
    target_frame: odom
    max_armor_distance: 5.0

    ekf:
      sigma2_q_xyz: 3e-2
      sigma2_q_yaw: 1.5e0
      sigma2_q_r: 25.0

      r_xyz_factor: 8e-3
      r_yaw: 4e-2

    tracker:
      max_match_distance: 0.15
      max_match_yaw_diff: 0.2

      tracking_thres: 32
      lost_time_thres: 0.15